In [154]:
import pandas as pd
df = pd.read_csv('pipelines.csv', sep='|')
df.columns = df.columns.str.strip()

In [155]:
COMPS = pd.read_csv('pipeline-comps.csv', sep='|')
SRCS = pd.read_csv('pipeline-sources.csv', sep='|')

In [156]:
COMPS

    ord   comp_label  gloss
0     1   Understand    NaN
1     2         Plan    NaN
2     3      Collect    NaN
3     4        Store    NaN
4     5        Clean    NaN
5     6      Explore    NaN
6     7      Prepare    NaN
7     8        Model    NaN
8     9    Interpret    NaN
9    10  Communicate    NaN
10   11       Deploy    NaN
11   12      Reflect    NaN

In [157]:
SRCS

,source_id,n_phases,ref
0,Porter 2020,8,"Porter, Michael. 2021. Personal communication."
1,Géron 2107,8,"Géron, Aurélien. 2017. Hands-On Machine Learni..."
2,Donaho 2017,7,"Donoho, David. 2017. “50 Years of Data Science..."
3,Das 2019,7,"Das, Sangeet Moy. 2019. “Data Science Life Cyc..."
4,CRISP-DM,7,"Wirth, Rüdiger, and Jochen Hipp. 1999. “CRISP-..."
5,Dataman 2020,7,"Dataman, Dr. 2020. “Data Science Modeling Proc..."
6,CPL 2018,6,"Caffo, Brian, Roger D. Peng, and Jeffrey Leek...."
7,Fayyad et al 1996,6,"Fayyad, Usama M, Gregory Piatetsky-Shapiro, Pa..."
8,Ojeda et al 2014,6,"Ojeda, Tony, Sean Patrick Murphy, Benjamin Ben..."
9,Wiggins 2010,5,"Mason, Hilary, and Christopher Wiggins. 2010. ..."
10,Hayashi 1996,3,"Hayashi, Chikio. 1998. “What Is Data Science? ..."
11,Tukey 1962,3,"Tukey, John W. 1962. “The Future of Data Analy..."

In [158]:
df.comp_label = df.comp_label.str.strip()
df = df.set_index(['source_id','comp_label'])

In [159]:
df

                                   source_label
source_id    comp_label
Hayashi 1996 Understand                  Design
             Collect                    Collect
             Model                      Analyze
Wiggins 2010 Collect                     Obtain
             Clean                        Scrub
...                                         ...
Dataman 2020 Collect                 Collection
             Explore                        EDA
             Model                     Modeling
             Interpret               Evaluation
             Deploy      Deployment; Monitoring

[73 rows x 1 columns]

In [161]:
cols = COMPS.sort_values('ord').comp_label
df.source_label.unstack(fill_value='')[cols].to_html("pipelines.html")

# What to Show

1. Each source described and with sequence
2. Description of composite labels
3. Table of sources and composite labels